// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#pragma once

#include "cpp_exception.hpp"
#include <memory>

namespace testsuite {

public ref class CppException sealed : public Platform::Object
{
public:
    int32 ThrowAnException ();
    static CppException^ Get ();
internal:
    CppException(std::shared_ptr<::testsuite::CppException> cppRef) : _cppRef(cppRef) {}
    std::shared_ptr<::testsuite::CppException> cppRef() {return _cppRef;}
private:
    std::shared_ptr<::testsuite::CppException> _cppRef;
};

}  // namespace testsuite
